# Generated by Django 4.2.18 on 2025-04-14 05:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='user_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
        migrations.CreateModel(
            name='UserLeadInfo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.CharField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('work_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf_brazil', models.CharField(blank=True, max_length=50, null=True)),
                ('dni_argentina', models.CharField(blank=True, max_length=50, null=True)),
                ('dni_peru', models.CharField(blank=True, max_length=50, null=True)),
                ('rut_chile', models.CharField(blank=True, max_length=50, null=True)),
                ('ci_ecuador', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc_mexico', models.CharField(blank=True, max_length=50, null=True)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserFieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_fields', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
    ]
