# Generated by Django 4.2.18 on 2025-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_geolocation_interest_promotedobject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
