# Generated by Django 4.2.18 on 2025-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ad_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleadinfo',
            name='ad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userleadinfo',
            name='form_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userleadinfo',
            name='lead_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
