# Generated by Django 4.2.18 on 2025-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userdata_tokendate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendate',
            name='long_time_access_token',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='tokendate',
            name='short_time_access_token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
