# Generated by Django 4.2.18 on 2025-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userleadinfo_ad_id_userleadinfo_form_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
