# Generated by Django 4.2.18 on 2025-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_listofkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfieldaccess',
            name='allowed_fields',
        ),
        migrations.AddField(
            model_name='userfieldaccess',
            name='allowed_fields',
            field=models.ManyToManyField(blank=True, null=True, to='app.listofkeys'),
        ),
    ]
