# Generated by Django 4.2.18 on 2025-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userfieldaccess_allowed_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfieldaccess',
            name='allowed_fields',
            field=models.ManyToManyField(blank=True, to='app.listofkeys'),
        ),
    ]
