# Generated by Django 4.2.18 on 2025-04-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_leadgendata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255)),
                ('api_version', models.CharField(blank=True, max_length=10, null=True)),
                ('form_id', models.IntegerField()),
                ('campaign_id', models.BigIntegerField()),
                ('adgroup_id', models.BigIntegerField(blank=True, null=True)),
                ('creative_id', models.BigIntegerField(blank=True, null=True)),
                ('gcl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('google_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleLeadAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_id', models.CharField(max_length=100)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('string_value', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.googlelead')),
            ],
        ),
    ]
