# Generated by Django 4.2.18 on 2025-04-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_googlelead_googleleadanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlelead',
            name='user_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userdata'),
        ),
    ]
