# Generated by Django 4.2.18 on 2025-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_googlelead_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlelead',
            name='lead_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
